version: "3.1"
services:
  os:
    image:  dockercore/opensuse:12.3
  db:
    image: mariadb
    deploy:
      restart_policy:
         condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
